//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_control_no
    {
        public string control_type { get; set; }
        public string control_code { get; set; }
        public string control_desc { get; set; }
        public string control_digit { get; set; }
        public Nullable<decimal> last_seq_no { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    }
}
