//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_UserMenuList
    {
        public int sysId { get; set; }
        public string sysname { get; set; }
        public int menuId { get; set; }
        public string menuname { get; set; }
        public string MENUPARENT { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> menuorder { get; set; }
        public string viewtype { get; set; }
        public string prtmenucode { get; set; }
        public Nullable<bool> istransaction { get; set; }
        public string menutype { get; set; }
        public string nenunames { get; set; }
        public int userId { get; set; }
        public Nullable<bool> canadd { get; set; }
        public Nullable<bool> canedit { get; set; }
        public Nullable<bool> candelete { get; set; }
        public Nullable<bool> canview { get; set; }
        public Nullable<bool> canopen { get; set; }
        public int Expr1 { get; set; }
        public int SUBTOTAL { get; set; }
        public string MENUTYPEDES { get; set; }
        public Nullable<bool> forweb { get; set; }
        public Nullable<int> ParentMenuOrder { get; set; }
        public string syscode { get; set; }
        public string sysdescription { get; set; }
        public string ParentIcon { get; set; }
        public string ChildIcon { get; set; }
        public Nullable<bool> formobile { get; set; }
        public string menucode { get; set; }
    }
}
