//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_confirmation
    {
        public int confirmId { get; set; }
        public string confirmtype { get; set; }
        public string confirmcode { get; set; }
        public string referencecode { get; set; }
        public Nullable<System.DateTime> expirydate { get; set; }
        public Nullable<bool> isconfirm { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
