//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_link
    {
        public int linkId { get; set; }
        public string uuid { get; set; }
        public string description { get; set; }
        public System.DateTime expirydate { get; set; }
        public bool isused { get; set; }
        public string recipientemail { get; set; }
        public string sourceapplication { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
