//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_system
    {
        public int Id { get; set; }
        public string debugpassword { get; set; }
        public int pismutilizationmonth { get; set; }
        public int pismutilizationyear { get; set; }
        public string mobadminpincode { get; set; }
    }
}
