//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_mailer
    {
        public int id { get; set; }
        public string senderDisplayEmail { get; set; }
        public string senderDisplayName { get; set; }
        public string recipient { get; set; }
        public string ccrecipient { get; set; }
        public string bccrecipient { get; set; }
        public string mailSubject { get; set; }
        public string mailBody { get; set; }
        public string filePath { get; set; }
        public string mailFormat { get; set; }
        public string mailStatus { get; set; }
        public string createdBy { get; set; }
        public System.DateTime created { get; set; }
    }
}
