//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_branchmst
    {
        public string brancode { get; set; }
        public string branname { get; set; }
        public string address { get; set; }
        public string status { get; set; }
        public string districtcode { get; set; }
        public string branchheadname { get; set; }
        public string branchheadcontact { get; set; }
        public string branalias { get; set; }
        public string mapreference { get; set; }
        public string branchheadid { get; set; }
        public string branchheademail { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string sbu { get; set; }
        public byte withpism { get; set; }
        public bool withwfmsdb { get; set; }
        public Nullable<int> wfmsdbId { get; set; }
        public byte reportflag { get; set; }
        public string hrisbranchcode { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<byte> isinclude { get; set; }
        public string brancharea { get; set; }
        public string region { get; set; }
        public Nullable<decimal> matrix { get; set; }
        public Nullable<decimal> additives { get; set; }
        public Nullable<decimal> reliever_rd { get; set; }
        public Nullable<decimal> projbase_bill { get; set; }
        public Nullable<decimal> sunday_ops { get; set; }
        public Nullable<decimal> reliever_absent { get; set; }
        public Nullable<decimal> nonmatrix { get; set; }
        public Nullable<decimal> projbase_notbill { get; set; }
        public Nullable<byte> isreportauto { get; set; }
        public string logcapturing { get; set; }
        public byte isnteonly { get; set; }
        public Nullable<decimal> matrixam { get; set; }
        public Nullable<decimal> matrixpm { get; set; }
        public Nullable<decimal> nonmatrixam { get; set; }
        public Nullable<decimal> nonmatrixpm { get; set; }
    
        public virtual core_district core_district { get; set; }
    }
}
