//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_employee
    {
        public string empl_id { get; set; }
        public string employeename { get; set; }
        public string employeename2 { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string status { get; set; }
        public string sex { get; set; }
        public string civilstatus { get; set; }
        public string emailadd { get; set; }
        public Nullable<System.DateTime> datehired { get; set; }
        public System.DateTime effectivitydate { get; set; }
        public string corporate { get; set; }
        public string corporateName { get; set; }
        public string branch { get; set; }
        public string branchname { get; set; }
        public string brancharea { get; set; }
        public string position { get; set; }
        public string positionname { get; set; }
        public string department { get; set; }
        public string departmentname { get; set; }
        public string section { get; set; }
        public string sectionname { get; set; }
        public string levelcode { get; set; }
        public string levelname { get; set; }
        public string joblevelgroup { get; set; }
        public string @class { get; set; }
        public string type { get; set; }
        public string typedescription { get; set; }
        public string employeepresentaddress { get; set; }
        public string employeehomeaddress { get; set; }
        public string employeepresentcontact { get; set; }
        public string homecontact { get; set; }
        public string ImmediateID { get; set; }
        public string ImmediateName { get; set; }
        public Nullable<System.DateTime> ImmediateBDay { get; set; }
        public string ImmediateStatus { get; set; }
        public string ImmediateEmail { get; set; }
        public Nullable<System.DateTime> ImmediateDHired { get; set; }
        public string ImmediateSBU { get; set; }
        public string ImmediateBranch { get; set; }
        public string ImmediatePosition { get; set; }
        public string ImmediateDepartment { get; set; }
        public string ImmediateSection { get; set; }
        public string ImmediateLevel { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string sss { get; set; }
    }
}
