//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fpma_member
    {
        public int Id { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> CatalystId { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public string sitecode { get; set; }
    }
}
