//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vMeeting
    {
        public int meetingId { get; set; }
        public int topicId { get; set; }
        public string TopicDescription { get; set; }
        public string agenda { get; set; }
        public string venue { get; set; }
        public string facilitator { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
        public int TotalExpectedAttendees { get; set; }
        public int TotalActualAttendees { get; set; }
        public int TotalMinuteCaptured { get; set; }
        public string YearNumber { get; set; }
        public string MonthNumber { get; set; }
        public string WeekNumber { get; set; }
    }
}
