//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vAccountValidation
    {
        public string empl_id { get; set; }
        public string employeename2 { get; set; }
        public string coreEmployeeEmail { get; set; }
        public string HRISEmail { get; set; }
        public string CoreUsername { get; set; }
        public string CoreEmail { get; set; }
        public string mifsMember { get; set; }
        public string ResponEmail { get; set; }
        public string RaisedbyEmail { get; set; }
        public string CollaboratorEmail { get; set; }
    }
}
