//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_respondent
    {
        public int respondentId { get; set; }
        public int issueId { get; set; }
        public string responsibleemailadd { get; set; }
        public string responsiblename { get; set; }
        public string responsiblephone { get; set; }
        public string responsibleemplid { get; set; }
        public string collaboratoremailadd { get; set; }
        public byte[] collaboratorname { get; set; }
        public string collaboratorphone { get; set; }
        public string collaboratoremplid { get; set; }
        public string status { get; set; }
        public string newstatus { get; set; }
        public Nullable<System.DateTime> parkdate { get; set; }
        public Nullable<System.DateTime> resumedate { get; set; }
        public Nullable<System.DateTime> firstsenddate { get; set; }
        public Nullable<System.DateTime> lastsenddate { get; set; }
        public Nullable<System.DateTime> commitmentdate { get; set; }
        public Nullable<System.DateTime> statchangeacknowledgementdate { get; set; }
        public bool statchangeresponsible { get; set; }
        public bool statchangetollgater { get; set; }
        public int statchangefupcounter { get; set; }
        public int fupcounter { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual mifs_issues mifs_issues { get; set; }
    }
}
