//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mifs_DailyUtilization
    {
        public Nullable<int> IssueCaptured { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
        public string CreatedBy { get; set; }
        public string BranchName { get; set; }
        public string DistrictName { get; set; }
    }
}
