//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vIssueReport
    {
        public int issueId { get; set; }
        public int CurrentTopicId { get; set; }
        public string CurrentTopicDescription { get; set; }
        public string Details { get; set; }
        public string actionplan { get; set; }
        public System.DateTime DateIssued { get; set; }
        public System.DateTime targetcompletiondate { get; set; }
        public string IssueStatus { get; set; }
        public int FollowUpCounter { get; set; }
        public Nullable<System.DateTime> IssueDateParked { get; set; }
        public Nullable<System.DateTime> IssueDateResumed { get; set; }
        public string reference { get; set; }
        public string raisedby { get; set; }
        public string raisedbyemail { get; set; }
        public string raisedbyempid { get; set; }
        public string raisedbyphone { get; set; }
        public string responsible { get; set; }
        public string responemail { get; set; }
        public string responempid { get; set; }
        public string responphone { get; set; }
        public string sourcetype { get; set; }
        public string TopicAlias { get; set; }
        public int followfrequency { get; set; }
        public byte followmail { get; set; }
        public string newstatus { get; set; }
        public byte acknowledgedbysource { get; set; }
        public Nullable<System.DateTime> acknowledgesourcedate { get; set; }
        public byte acknowledgebyrespondent { get; set; }
        public Nullable<System.DateTime> acknowledgerespondentdate { get; set; }
        public Nullable<System.DateTime> firstsenddate { get; set; }
        public Nullable<System.DateTime> lastsenddate { get; set; }
        public Nullable<int> statchangefupcounter { get; set; }
        public int meetingId { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string collaboratorname { get; set; }
        public string collaboratoremail { get; set; }
        public string collaboratorempid { get; set; }
        public string hashcode { get; set; }
        public byte pflag { get; set; }
        public byte issuetype { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> closedate { get; set; }
        public string referenceId { get; set; }
        public string referencetype { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string Updates { get; set; }
        public string ResponsivenessRating { get; set; }
    }
}
