//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vResponse
    {
        public int responseId { get; set; }
        public int issueId { get; set; }
        public int topicId { get; set; }
        public string issuedetails { get; set; }
        public string messagedetails { get; set; }
        public string responsebyempid { get; set; }
        public System.DateTime responsedate { get; set; }
        public string responseby { get; set; }
        public string responsebyemail { get; set; }
        public string raisedbyphone { get; set; }
        public string raisedbyempid { get; set; }
        public string raisedbyemail { get; set; }
        public string raisedby { get; set; }
        public string responsible { get; set; }
        public string responemail { get; set; }
        public string responempid { get; set; }
        public string responphone { get; set; }
        public Nullable<int> NoOfAttachment { get; set; }
        public bool islock { get; set; }
        public bool isdeleted { get; set; }
    }
}
