//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_Analytics
    {
        public int issueId { get; set; }
        public int CurrentTopicId { get; set; }
        public string CurrentTopicDescription { get; set; }
        public string Details { get; set; }
        public string actionplan { get; set; }
        public System.DateTime DateIssued { get; set; }
        public Nullable<int> PreviousTopicId { get; set; }
        public string PreviousTopicDescription { get; set; }
        public System.DateTime targetcompletiondate { get; set; }
        public int FollowUpFrequency { get; set; }
        public string IsFollowUpOnEmail { get; set; }
        public string IsFollowUpOnSMS { get; set; }
        public string IssueStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string newstatus { get; set; }
        public string IsAcknowledgeBySource { get; set; }
        public Nullable<System.DateTime> SourceAcknowledgeDate { get; set; }
        public string IsAcknowledgeByRespondent { get; set; }
        public Nullable<System.DateTime> RespondentAcknowledgeDate { get; set; }
        public int FollowUpCounter { get; set; }
        public Nullable<System.DateTime> IssueDateParked { get; set; }
        public Nullable<System.DateTime> IssueDateResumed { get; set; }
        public Nullable<int> NoOfAttachment { get; set; }
        public string IssueHashcode { get; set; }
        public Nullable<int> meetingId { get; set; }
        public string agenda { get; set; }
        public Nullable<System.DateTime> datestart { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public string venue { get; set; }
        public string facilitator { get; set; }
        public string reference { get; set; }
        public string TopicHashcode { get; set; }
        public string raisedby { get; set; }
        public string raisedbyemail { get; set; }
        public string raisedbyempid { get; set; }
        public string raisedbyphone { get; set; }
        public string responsible { get; set; }
        public string responemail { get; set; }
        public string responempid { get; set; }
        public string responphone { get; set; }
        public string sourcetype { get; set; }
        public Nullable<System.DateTime> lastsenddate { get; set; }
        public Nullable<int> NoOfResponse { get; set; }
        public byte PriorityFlag { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string Collaborator { get; set; }
        public string TypeOfIssue { get; set; }
        public string category { get; set; }
        public string TopicAlias { get; set; }
        public string bgcolor { get; set; }
        public string collaboratoremail { get; set; }
        public string collaboratorempid { get; set; }
        public int HasResponseAttachment { get; set; }
        public string referenceId { get; set; }
        public string referencetype { get; set; }
        public Nullable<int> DaysElapse { get; set; }
        public string IsOverdue { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> LastTollgated { get; set; }
        public Nullable<int> Responsiveness { get; set; }
        public Nullable<int> TollGaterResponsiveness { get; set; }
        public int AcknowledgementDays { get; set; }
        public string ResponsibleImmediateHead { get; set; }
        public string TollGaterImmediateHead { get; set; }
        public string BranchName { get; set; }
        public string DistrictName { get; set; }
        public string LastUpdateMessage { get; set; }
        public string LastUpdateBy { get; set; }
        public string LastUpdateMessageByCollaborator { get; set; }
        public Nullable<System.DateTime> LastUpdateDateByCollaborator { get; set; }
        public string BranchCode { get; set; }
        public string CorporateCode { get; set; }
        public string CorporateName { get; set; }
        public string IssueCategory { get; set; }
        public string JobLevelGroup { get; set; }
        public string Position { get; set; }
        public string WeekCreated { get; set; }
        public string EncoderBranch { get; set; }
    }
}
