//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vIssuePerWeekPerStatus
    {
        public Nullable<long> id { get; set; }
        public Nullable<int> TotalOpen { get; set; }
        public Nullable<int> TotalClosed { get; set; }
        public Nullable<int> TotalParked { get; set; }
        public Nullable<int> TotalDropped { get; set; }
        public int CurrentTopicId { get; set; }
        public string CurrentTopicDescription { get; set; }
        public Nullable<int> IssuedYear { get; set; }
        public Nullable<int> IssuedMonth { get; set; }
        public Nullable<int> IssuedWeek { get; set; }
        public Nullable<int> CurrentYear { get; set; }
        public Nullable<int> CurrentMonth { get; set; }
        public Nullable<int> CurrentWeek { get; set; }
    }
}
