//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vMeetingSchedule
    {
        public int meetingId { get; set; }
        public string hashcode { get; set; }
        public int topicId { get; set; }
        public string agenda { get; set; }
        public System.DateTime datestart { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public string venue { get; set; }
        public string facilitator { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string memberId { get; set; }
        public Nullable<int> yr { get; set; }
        public Nullable<int> month { get; set; }
        public string aliascode { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> followupday { get; set; }
        public Nullable<System.DateTime> followuphour { get; set; }
        public string emailaddress { get; set; }
    }
}
