//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_ladder
    {
        public int id { get; set; }
        public int totalopen { get; set; }
        public int totalclosed { get; set; }
        public int totalparked { get; set; }
        public int totaldropped { get; set; }
        public Nullable<int> topicid { get; set; }
        public string topicdesc { get; set; }
        public Nullable<int> issuedyear { get; set; }
        public Nullable<int> issuedmonth { get; set; }
        public Nullable<int> issuedweek { get; set; }
        public Nullable<int> capturedyear { get; set; }
        public Nullable<int> capturedmonth { get; set; }
        public Nullable<int> capturedweek { get; set; }
        public Nullable<System.DateTime> rundate { get; set; }
    }
}
