//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_FollowUpOpen
    {
        public int topicId { get; set; }
        public string description { get; set; }
        public int issueId { get; set; }
        public string issuedetails { get; set; }
        public string actionplan { get; set; }
        public System.DateTime issuedate { get; set; }
        public System.DateTime targetcompletiondate { get; set; }
        public Nullable<System.DateTime> lastsenddate { get; set; }
        public string raisedby { get; set; }
        public string raisedbyemail { get; set; }
        public string raisedbyphone { get; set; }
        public string responsible { get; set; }
        public string responemail { get; set; }
        public string responphone { get; set; }
        public int followfrequency { get; set; }
        public byte followmail { get; set; }
        public byte followsms { get; set; }
    }
}
