//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_response
    {
        public int responseId { get; set; }
        public int issueId { get; set; }
        public string messagedetails { get; set; }
        public string responseby { get; set; }
        public string responsebyempid { get; set; }
        public System.DateTime responsedate { get; set; }
        public string responsebyemail { get; set; }
        public bool islock { get; set; }
        public bool isdeleted { get; set; }
        public Nullable<bool> istypeaction { get; set; }
    
        public virtual mifs_issues mifs_issues { get; set; }
    }
}
