//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vIssueTrendMonthly
    {
        public string CurrentTopicDescription { get; set; }
        public Nullable<int> IssuedYear { get; set; }
        public Nullable<int> IssuedMonth { get; set; }
        public Nullable<int> Open { get; set; }
        public Nullable<int> Parked { get; set; }
        public Nullable<int> Closed { get; set; }
        public Nullable<int> Dropped { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
