//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vOpenIssuePerWeek
    {
        public Nullable<int> Total { get; set; }
        public string CurrentTopicDescription { get; set; }
        public Nullable<int> IssuedYear { get; set; }
        public string IssuedMonth { get; set; }
        public Nullable<int> IssuedWeek { get; set; }
        public Nullable<int> CurrentYear { get; set; }
        public string CurrentMonth { get; set; }
        public Nullable<int> CurrentWeek { get; set; }
    }
}
