//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_dropdown
    {
        public int id { get; set; }
        public string code { get; set; }
        public string value { get; set; }
        public string display { get; set; }
        public string details { get; set; }
        public Nullable<int> leadtimemin { get; set; }
        public Nullable<int> leadtimemax { get; set; }
        public Nullable<int> sortorder { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> lookup { get; set; }
        public string status { get; set; }
        public byte isdelete { get; set; }
    }
}
