//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vFirmAttendance
    {
        public Nullable<int> Meeting_ID { get; set; }
        public string Topic_Name { get; set; }
        public string Topic_Created_Date { get; set; }
        public string Attendee { get; set; }
        public byte Is_member { get; set; }
        public byte Is_present { get; set; }
        public string Logdate { get; set; }
        public string LogTime { get; set; }
    }
}
