//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vTopicMembers
    {
        public int topicId { get; set; }
        public string TopicDescription { get; set; }
        public string memberId { get; set; }
        public string MemberName { get; set; }
        public string MemberMobileNumber { get; set; }
        public string MemberEmailAddress { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string nickname { get; set; }
        public string status { get; set; }
        public Nullable<int> fupfrequency { get; set; }
        public Nullable<int> sourcelevel { get; set; }
        public string hashcode { get; set; }
        public string occurence { get; set; }
        public string bgcolor { get; set; }
        public string accesslevel { get; set; }
        public byte isinclude { get; set; }
    }
}
