//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vIssueCount
    {
        public int CurrentTopicId { get; set; }
        public string CurrentTopicDescription { get; set; }
        public string IssueStatus { get; set; }
        public Nullable<int> TotalIssues { get; set; }
        public string responemail { get; set; }
        public string raisedbyemail { get; set; }
        public string collaboratoremail { get; set; }
        public int topicId { get; set; }
        public string TopicAlias { get; set; }
    }
}
