//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mifs_meeting()
        {
            this.mifs_attendance = new HashSet<mifs_attendance>();
        }
    
        public int meetingId { get; set; }
        public string hashcode { get; set; }
        public int topicId { get; set; }
        public string agenda { get; set; }
        public System.DateTime datestart { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public string venue { get; set; }
        public string facilitator { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string closedby { get; set; }
        public Nullable<System.DateTime> closedate { get; set; }
        public byte issent { get; set; }
        public byte isattendance { get; set; }
        public byte iscancel { get; set; }
        public Nullable<System.DateTime> scheduledatestart { get; set; }
        public Nullable<System.DateTime> scheduledateend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mifs_attendance> mifs_attendance { get; set; }
        public virtual mifs_topic mifs_topic { get; set; }
    }
}
