//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_issues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mifs_issues()
        {
            this.mifs_respondent = new HashSet<mifs_respondent>();
            this.mifs_response = new HashSet<mifs_response>();
        }
    
        public int issueId { get; set; }
        public string hashcode { get; set; }
        public int topicId { get; set; }
        public string issuedetails { get; set; }
        public string actionplan { get; set; }
        public System.DateTime issuedate { get; set; }
        public Nullable<int> fromtopicId { get; set; }
        public System.DateTime targetcompletiondate { get; set; }
        public string raisedby { get; set; }
        public string raisedbyemail { get; set; }
        public string raisedbyempid { get; set; }
        public string raisedbyphone { get; set; }
        public string responsible { get; set; }
        public string responemail { get; set; }
        public string responempid { get; set; }
        public string responphone { get; set; }
        public int followfrequency { get; set; }
        public byte followmail { get; set; }
        public byte followsms { get; set; }
        public string status { get; set; }
        public string newstatus { get; set; }
        public byte acknowledgedbysource { get; set; }
        public Nullable<System.DateTime> acknowledgesourcedate { get; set; }
        public byte acknowledgebyrespondent { get; set; }
        public Nullable<System.DateTime> acknowledgerespondentdate { get; set; }
        public int fupcounter { get; set; }
        public Nullable<System.DateTime> parkdate { get; set; }
        public Nullable<System.DateTime> resumedate { get; set; }
        public Nullable<System.DateTime> firstsenddate { get; set; }
        public Nullable<System.DateTime> lastsenddate { get; set; }
        public Nullable<int> statchangefupcounter { get; set; }
        public int meetingId { get; set; }
        public string reference { get; set; }
        public string sourcetype { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string collaboratorname { get; set; }
        public string collaboratoremail { get; set; }
        public string collaboratorempid { get; set; }
        public byte pflag { get; set; }
        public byte issuetype { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> closedate { get; set; }
        public string referenceId { get; set; }
        public string referencetype { get; set; }
        public string refsource { get; set; }
        public string issuecategory { get; set; }
        public string branchcode { get; set; }
        public Nullable<int> fromissueid { get; set; }
        public string districtcode { get; set; }
        public string quadrant { get; set; }
        public string subkpi { get; set; }
        public Nullable<int> reviewlevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mifs_respondent> mifs_respondent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mifs_response> mifs_response { get; set; }
    }
}
