//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vParking
    {
        public string Responsible { get; set; }
        public int IssueId { get; set; }
        public System.DateTime TrailOfCommitment { get; set; }
        public int TopicId { get; set; }
        public string TopicDescription { get; set; }
        public string Issue { get; set; }
        public string ActionPlan { get; set; }
        public string Tollgater { get; set; }
        public string Collaborator { get; set; }
        public string IssueStatus { get; set; }
        public System.DateTime DateParked { get; set; }
    }
}
