//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vClosedPerResponsible
    {
        public int issueId { get; set; }
        public int topicId { get; set; }
        public string responempid { get; set; }
        public string responsible { get; set; }
        public System.DateTime issuedate { get; set; }
        public string WeekNumber { get; set; }
        public string MonthNumber { get; set; }
        public string YearNumber { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string DistrictName { get; set; }
    }
}
