//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vNotMember
    {
        public string empl_id { get; set; }
        public string employeename2 { get; set; }
        public string emailadd { get; set; }
        public string positionname { get; set; }
        public string employeepresentcontact { get; set; }
        public string corporate { get; set; }
    }
}
