//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vIssueClosedPerEmployeeX
    {
        public string PaloType { get; set; }
        public Nullable<int> TotalClosed { get; set; }
        public string EmailAdd { get; set; }
        public string FullName { get; set; }
        public Nullable<int> YearClosed { get; set; }
        public Nullable<int> MonthClosed { get; set; }
        public string EmployeeId { get; set; }
    }
}
