//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_topicmembers
    {
        public int topicId { get; set; }
        public string memberId { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string accesslevel { get; set; }
        public byte isinclude { get; set; }
    
        public virtual mifs_topic mifs_topic { get; set; }
    }
}
