//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_members
    {
        public string memberId { get; set; }
        public string fullname { get; set; }
        public string emailaddress { get; set; }
        public string mobileno { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
        public string nickname { get; set; }
        public string status { get; set; }
        public Nullable<int> sysId { get; set; }
        public string systemname { get; set; }
    }
}
