//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mifs_vTopicLevel
    {
        public string parent_code { get; set; }
        public string child_code { get; set; }
        public string levelcode { get; set; }
        public string description { get; set; }
        public string level { get; set; }
        public byte status { get; set; }
    }
}
