//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ole_examinee
    {
        public int examineeId { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string sex { get; set; }
        public System.DateTime birthdate { get; set; }
        public string sbu { get; set; }
        public string area { get; set; }
        public string branch { get; set; }
        public string status { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string nickname { get; set; }
        public string chnickflag { get; set; }
        public string hashcode { get; set; }
        public string joblevel { get; set; }
        public string employeeid { get; set; }
    }
}
