//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_servers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wms_servers()
        {
            this.wms_serverwarehouses = new HashSet<wms_serverwarehouses>();
        }
    
        public int serverId { get; set; }
        public string servername { get; set; }
        public string dbname { get; set; }
        public string ipaddress { get; set; }
        public string webaddress { get; set; }
        public string sqluser { get; set; }
        public string sqlpass { get; set; }
        public string status { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wms_serverwarehouses> wms_serverwarehouses { get; set; }
    }
}
