//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_serverwarehouses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wms_serverwarehouses()
        {
            this.wms_userserverwarehouse = new HashSet<wms_userserverwarehouse>();
        }
    
        public int serverwarehouseId { get; set; }
        public int serverId { get; set; }
        public string warehousecode { get; set; }
        public string brancode { get; set; }
        public string storageidentity { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wms_userserverwarehouse> wms_userserverwarehouse { get; set; }
        public virtual wms_servers wms_servers { get; set; }
    }
}
