//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaloUpAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wms_userserverwarehouse
    {
        public int userId { get; set; }
        public int serverwarehouseId { get; set; }
        public string username { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual core_users core_users { get; set; }
        public virtual wms_serverwarehouses wms_serverwarehouses { get; set; }
    }
}
